version: "3.9"

services:
  app:
    container_name: dream-gpt-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      CHOKIDAR_USEPOLLING: "true" # Docker 内での watcher を安定させる
    command: bun run start
